# Generated by Django 3.2 on 2022-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skincare',
            name='skin_concern',
        ),
        migrations.RemoveField(
            model_name='skincare',
            name='star_ingredient',
        ),
        migrations.AlterField(
            model_name='skincare',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='skin_type',
            field=models.CharField(choices=[('NORMAL_SKIN', 'Normal'), ('DRY_SKIN', 'Dry'), ('COMBINATION_SKIN', 'Combination'), ('OILY_SKIN', 'Oily'), ('SENSITIVE_SKIN', 'Sensitive')], max_length=500),
        ),
    ]
